version: "3.7"
services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./config:/etc/traefik/dynamic/      # If needed
    labels:
      - traefik.enable=true

  manager:
    image: adyanth/traefik-container-manager-service
    expose: 
      - 10000
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels: 
      - traefik.enable=true
      - traefik.http.routers.manager.entrypoints=web
      - traefik.http.routers.manager.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.manager.priority=1
      - traefik.http.middlewares.manager.errors.status=404
      - traefik.http.middlewares.manager.errors.service=manager
      - traefik.http.middlewares.manager.errors.query=/
      - traefik.http.routers.manager.middlewares=manager-timeout
      - traefik.http.services.manager.loadbalancer.server.port=80
      - traefik.http.middlewares.manager-timeout.plugin.traefik-container-manager.Name=generic-container-manager
      - traefik.http.middlewares.manager-timeout.plugin.traefik-container-manager.ServiceUrl=http://manager:10000/api

  whoami:
    image: containous/whoami
    labels: 
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.rule=Host(`whoami.adyanth.lan`) || PathPrefix(`/whoami`)
      - traefik.http.routers.whoami.middlewares=whoami-timeout
      - traefik.http.middlewares.whoami-timeout.plugin.traefik-container-manager.timeout=5
      - traefik.http.middlewares.whoami-timeout.plugin.traefik-container-manager.name=whoami
      - traefik.http.middlewares.whoami-timeout.plugin.traefik-container-manager.ServiceUrl=http://manager:10000/api
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik-container-manager.name=whoami
      - traefik-container-manager.path=/whoami # Prefix matched to the incoming path.
      - traefik-container-manager.host=whoami # Prefix matched to the incoming hostname. Can provide the subdomain or the complete fqdn.
